"""Constants matching Cloudflare Pages limits and defaults."""

MAX_ASSET_SIZE = 25 * 1024 * 1024  # 25 MiB
MAX_ASSET_COUNT = 20_000
MAX_BUCKET_SIZE = 40 * 1024 * 1024  # 40 MiB
MAX_BUCKET_FILE_COUNT = 2_000
BULK_UPLOAD_CONCURRENCY = 3

MAX_UPLOAD_ATTEMPTS = 5
MAX_CHECK_MISSING_ATTEMPTS = 5
MAX_DEPLOYMENT_ATTEMPTS = 3
MAX_DEPLOYMENT_STATUS_ATTEMPTS = 5

MAX_COMMIT_MESSAGE_BYTES = 384

CF_API_BASE_URL = "https://api.cloudflare.com/client/v4"
